cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    awdawd:
      email: awd@awd.ch
      failed_login_attempts: 0
      logged_in: 0
      name: awd
      password: $2b$12$STdMKXKvJoAxDpN1Da/JnO.9gGw6Awu/OMtMeU9../BikadcMisAu
    awdawdaaaaa:
      email: awdawd@awdawda.ch
      failed_login_attempts: 0
      logged_in: 0
      name: awdawdddawdawdddddd
      password: your_password_here
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: 0
      name: John Smith
      password: $2b$12$ammV.cqPjGAR7nPJX0fZd.gVd4aNN9BcEgk3Ldn4A1Itn.mWE/Xiu
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: 0
      name: Rebecca Briggs
      password: $2b$12$/yzg52ggFrZlZJSOJgoEN.6rlxJC9IvnVkA8VHwDgEQwv8x9wNfOu
preauthorized:
  emails:
  - melsby@gmail.com
